### ISSUE TITLE
Fortis-Insights library should export existing charts

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/fortis-insights#2]
This library should export all visualization chart components as separate components, similar to recharts https://github.com/recharts/recharts/blob/master/src/index.js . 

If clients add a dependency to this chart in npm, then they should have the flexibility for importing the specified components.

**Comment by c-w** [comment]
We currently have a bunch of files relating to an App (likely due to using `react-create-app` to create this package). To implement the componentized chart export, we'll need a clean index.js so our current approach were we [spin up the App](https://github.com/CatalystCode/fortis-insights/blob/ce949d38ba426266154b6262dbfd21aee16bfa4f/src/index.js#L7) inside of index.js won't work.

**Comment by c-w** [comment]
This is implemented by #6
